module.exports = {
  extends: "stylelint-config-standard",
  defaultSeverity: 'error',
  rules: {
    "block-no-empty": null,
    // "color-no-invalid-hex": true,
    // "comment-empty-line-before": [ "always", {
    //   "ignore": ["stylelint-commands", "between-comments"],
    // } ],
    // "declaration-colon-space-after": "always",
    "max-empty-lines": null,
    // "rule-nested-empty-line-before": [ "always", {
    //   "except": ["first-nested"],
    //   "ignore": ["after-comment"],
    // } ],
    // 允许的单位
    "unit-whitelist": null,
    "unit-case": null,
    "block-closing-brace-empty-line-before": null,
    "block-closing-brace-newline-after": null,
    "block-closing-brace-newline-before": null,
    "block-closing-brace-space-before": null,
    "block-opening-brace-newline-after": null,
    "block-opening-brace-space-after": null,
    "block-opening-brace-space-before": null,
    "declaration-block-semicolon-newline-after": null,
    "declaration-block-semicolon-space-after": null,
    "declaration-block-semicolon-space-before": null,
    "declaration-block-trailing-semicolon": null,

    "declaration-colon-space-after": null,
    "rule-empty-line-before": null,
    "selector-pseudo-element-colon-notation": null,
    "declaration-colon-space-after": null,
    "number-leading-zero": null,
    "at-rule-empty-line-before": null,
    "selector-list-comma-newline-after": null,
    "indentation": [ null, { 
        "severity": "error",
        "message": "Please use 211 spaces for indentation. Tabs make The Architect grumpy.",
    } ],
    "color-hex-case": null,
    "function-comma-space-before": null,
    "color-hex-length": null,
    "declaration-colon-newline-after": null,
    "font-family-no-missing-generic-family-keyword": null,
    "no-missing-end-of-source-newline": null,
    "function-comma-space-after": null,
    "comment-empty-line-before": null,
    "declaration-block-single-line-max-declarations": null,
    "length-zero-no-unit": null,
    "value-list-comma-space-after": null,
    "comment-whitespace-inside": null,
    "no-eol-whitespace": null,
    "value-list-comma-space-after": null,
    "no-eol-whitespace": null,
    "at-rule-no-unknown": null,
    "declaration-bang-space-before": null,
    "no-descending-specificity": null,
  }
};